// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA33eZWu0yq2xaOH72eKcTK40qh5yOdsKc',
    appId: '1:1000820839956:web:1491116a851a85a022b901',
    messagingSenderId: '1000820839956',
    projectId: 'authenticationapp-ec67b',
    authDomain: 'authenticationapp-ec67b.firebaseapp.com',
    storageBucket: 'authenticationapp-ec67b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArarxFedUE1FqAmNDhEUaF975v4S5mPo0',
    appId: '1:1000820839956:android:487100ea809e817622b901',
    messagingSenderId: '1000820839956',
    projectId: 'authenticationapp-ec67b',
    storageBucket: 'authenticationapp-ec67b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCXuncB2EH3TAvLc1v0p_VgwY5wk9nuXU',
    appId: '1:1000820839956:ios:9d76e35a6600b81522b901',
    messagingSenderId: '1000820839956',
    projectId: 'authenticationapp-ec67b',
    storageBucket: 'authenticationapp-ec67b.appspot.com',
    iosBundleId: 'com.example.myactivityapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCXuncB2EH3TAvLc1v0p_VgwY5wk9nuXU',
    appId: '1:1000820839956:ios:33fdcabf6c4ce5e222b901',
    messagingSenderId: '1000820839956',
    projectId: 'authenticationapp-ec67b',
    storageBucket: 'authenticationapp-ec67b.appspot.com',
    iosBundleId: 'com.example.myactivityapp.RunnerTests',
  );
}
